### ISSUE TITLE
Set published and modified dates correctly

### ISSUE THREAD

**Issue by xaur** [block-commons/block-commons#24]
Found in the source of https://blockcommons.red/publication/mm-tracking-1/

```
<meta property="article:published_time" content="2017-01-01T00:00:00&#43;00:00">
<meta property="article:modified_time" content="2020-04-20T00:00:00&#43;00:00">
```

The same published date value is copied to the LD JSON:

```
<script type="application/ld+json">
{
...
  "datePublished": "2017-01-01T00:00:00Z",
  "dateModified": "2019-11-16T00:00:00Z",
...
}
</script>
```

Also note how `modified_time` is different from `dateModified`.

Incorrect metadata may affect the behavior of search engines, confuses web scraping and sometimes confuses people.

I suggest to set the published date to the date when the post was initiall released, and the modified date to the last modification date (which is equal to the published date if there was none).

**Comment by xaur** [comment]
The `&#43;` is also quite weird in the `<meta>` tag. I don't remember seeing it anywhere else. Should be `+`.

**Comment by jholdstock** [comment]
#26 fixes this. 

```
<meta property="article:published_time" content="2019-11-16T00:00:00">
<meta property="article:modified_time" content="2019-11-20T00:27:01">
```

```
<script type="application/ld+json">
{
...
    "datePublished": "2019-11-16T00:00:00Z",
    "dateModified": "2019-11-20T00:27:01Z",
...
}
</script>
```
